### ISSUE TITLE
Media Fragments

### ISSUE THREAD

**Issue by heff** [brightcove/videojs-urlparams#1]
Good stuff! Looking forward to playing around with this.

It looks like you're following the youtube API, which seems like the most well known. Have you heard of/considered the media fragments API for this at all?
http://www.w3.org/TR/media-frags/#valid-uri

**Comment by bcjwilson** [comment]
I had not heard of that. Seems interesting. A lot more work to implement. :(

**Comment by gkatsev** [comment]
https://github.com/tomayac/Media-Fragments-URI/
